# Get Data

In [11]:
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import os
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

# Show all columns
pd.set_option('display.max_columns', 150)
pd.set_option('display.width', 100)

UTZ raises exception: Too Many Requests. Rate limited. Try after a while.VSTS raises exception: Too Many Requests. Rate limited. Try after a while.
EQBK raises exception: Too Many Requests. Rate limited. Try after a while.
PFLT raises exception: Too Many Requests. Rate limited. Try after a while.
BTQ raises exception: Too Many Requests. Rate limited. Try after a while.
HLX raises exception: Too Many Requests. Rate limited. Try after a while.
NTSK raises exception: Too Many Requests. Rate limited. Try after a while.
BCSF raises exception: Too Many Requests. Rate limited. Try after a while.
LOT raises exception: Too Many Requests. Rate limited. Try after a while.
FUBO raises exception: Too Many Requests. Rate limited. Try after a while.
NBN raises exception: Too Many Requests. Rate limited. Try after a while.
NKTR raises exception: Too Many Requests. Rate limited. Try after a while.
CPF raises exception: Too Many Requests. Rate limited. Try after a while.
MEG raises exception: Too Many Requests. Rate limited. Try after a while.
JBSS raises exception: Too Many Requests. Rate limited. Try after a while.
ASM raises exception: Too Many Requests. Rate limited. Try after a while.
STRD raises exception: Too Many Requests. Rate limited. Try after a while.
XIFR raises exception: Too Many Requests. Rate limited. Try after a while.
CPAC raises exception: Too Many Requests. Rate limited. Try after a while.
SIBN raises exception: Too Many Requests. Rate limited. Try after a while.
HFWA raises exception: Too Many Requests. Rate limited. Try after a while.
GES raises exception: Too Many Requests. Rate limited. Try after a while.
AVBP raises exception: Too Many Requests. Rate limited. Try after a while.
ABUS raises exception: Too Many Requests. Rate limited. Try after a while.
BFLY raises exception: Too Many Requests. Rate limited. Try after a while.
HBT raises exception: Too Many Requests. Rate limited. Try after a while.
FBRT raises exception: Too Many Requests. Rate limited. Try after a while.
OLPX raises exception: Too Many Requests. Rate limited. Try after a while.
APOG raises exception: Too Many Requests. Rate limited. Try after a while.
GOTU raises exception: Too Many Requests. Rate limited. Try after a while.
AMTB raises exception: Too Many Requests. Rate limited. Try after a while.
HAFC raises exception: Too Many Requests. Rate limited. Try after a while.
FLGT raises exception: Too Many Requests. Rate limited. Try after a while.
MOFG raises exception: Too Many Requests. Rate limited. Try after a while.
ITRN raises exception: Too Many Requests. Rate limited. Try after a while.
NRGV raises exception: Too Many Requests. Rate limited. Try after a while.
MNTN raises exception: Too Many Requests. Rate limited. Try after a while.
WOOF raises exception: Too Many Requests. Rate limited. Try after a while.
KURA raises exception: Too Many Requests. Rate limited. Try after a while.
GSM raises exception: Too Many Requests. Rate limited. Try after a while.
ABL raises exception: Too Many Requests. Rate limited. Try after a while.
SMP raises exception: Too Many Requests. Rate limited. Try after a while.
GERN raises exception: Too Many Requests. Rate limited. Try after a while.
METCB raises exception: Too Many Requests. Rate limited. Try after a while.
SLRC raises exception: Too Many Requests. Rate limited. Try after a while.
MAX raises exception: Too Many Requests. Rate limited. Try after a while.
BALY raises exception: Too Many Requests. Rate limited. Try after a while.
PSNY raises exception: Too Many Requests. Rate limited. Try after a while.
QNST raises exception: Too Many Requests. Rate limited. Try after a while.
MLTX raises exception: Too Many Requests. Rate limited. Try after a while.
JANX raises exception: Too Many Requests. Rate limited. Try after a while.
MATW raises exception: Too Many Requests. Rate limited. Try after a while.
ODP raises exception: Too Many Requests. Rate limited. Try after a while.
MCB raises exception: Too Many Requests. Rate limited. Try after a while.
SG raises exception: Too Many Requests. Rate limited. Try after a while.
OMDA raises exception: Too Many Requests. Rate limited. Try after a while.
SIFY raises exception: Too Many Requests. Rate limited. Try after a while.
RYI raises exception: Too Many Requests. Rate limited. Try after a while.
BFST raises exception: Too Many Requests. Rate limited. Try after a while.
TH raises exception: Too Many Requests. Rate limited. Try after a while.
REAX raises exception: Too Many Requests. Rate limited. Try after a while.
TDAY raises exception: Too Many Requests. Rate limited. Try after a while.
EPC raises exception: Too Many Requests. Rate limited. Try after a while.
VIR raises exception: Too Many Requests. Rate limited. Try after a while.
UTL raises exception: Too Many Requests. Rate limited. Try after a while.
NXDR raises exception: Too Many Requests. Rate limited. Try after a while.
GDYN raises exception: Too Many Requests. Rate limited. Try after a while.
AMWD raises exception: Too Many Requests. Rate limited. Try after a while.
SOC raises exception: Too Many Requests. Rate limited. Try after a while.
TRST raises exception: Too Many Requests. Rate limited. Try after a while.
CCNE raises exception: Too Many Requests. Rate limited. Try after a while.
ARVN raises exception: Too Many Requests. Rate limited. Try after a while.
SLDP raises exception: Too Many Requests. Rate limited. Try after a while.
AIV raises exception: Too Many Requests. Rate limited. Try after a while.
NMAX raises exception: Too Many Requests. Rate limited. Try after a while.
KROS raises exception: Too Many Requests. Rate limited. Try after a while.
IOVA raises exception: Too Many Requests. Rate limited. Try after a while.
VINP raises exception: Too Many Requests. Rate limited. Try after a while.
INNV raises exception: Too Many Requests. Rate limited. Try after a while.
ATUS raises exception: Too Many Requests. Rate limited. Try after a while.
GCI raises exception: Too Many Requests. Rate limited. Try after a while.
POET raises exception: Too Many Requests. Rate limited. Try after a while.
CARS raises exception: Too Many Requests. Rate limited. Try after a while.
MBWM raises exception: Too Many Requests. Rate limited. Try after a while.
MITP raises exception: Too Many Requests. Rate limited. Try after a while.
MITN raises exception: Too Many Requests. Rate limited. Try after a while.
NBBK raises exception: Too Many Requests. Rate limited. Try after a while.
GOLD raises exception: Too Many Requests. Rate limited. Try after a while.
FSBC raises exception: Too Many Requests. Rate limited. Try after a while.
LAR raises exception: Too Many Requests. Rate limited. Try after a while.
CAPL raises exception: Too Many Requests. Rate limited. Try after a while.
YDES raises exception: Too Many Requests. Rate limited. Try after a while.
LDI raises exception: Too Many Requests. Rate limited. Try after a while.
HTB raises exception: Too Many Requests. Rate limited. Try after a while.
AXL raises exception: Too Many Requests. Rate limited. Try after a while.
METC raises exception: Too Many Requests. Rate limited. Try after a while.
DNUT raises exception: Too Many Requests. Rate limited. Try after a while.
JMIA raises exception: Too Many Requests. Rate limited. Try after a while.
HIPO raises exception: Too Many Requests. Rate limited. Try after a while.
CBLL raises exception: Too Many Requests. Rate limited. Try after a while.
GNK raises exception: Too Many Requests. Rate limited. Try after a while.
GHRS raises exception: Too Many Requests. Rate limited. Try after a while.
BLDP raises exception: Too Many Requests. Rate limited. Try after a while.
ORIC raises exception: Too Many Requests. Rate limited. Try after a while.
HNRG raises exception: Too Many Requests. Rate limited. Try after a while.
FWRD raises exception: Too Many Requests. Rate limited. Try after a while.
CAC raises exception: Too Many Requests. Rate limited. Try after a while.
TK raises exception: Too Many Requests. Rate limited. Try after a while.
CMP raises exception: Too Many Requests. Rate limited. Try after a while.
SNCY raises exception: Too Many Requests. Rate limited. Try after a while.
BLND raises exception: Too Many Requests. Rate limited. Try after a while.
RDVT raises exception: Too Many Requests. Rate limited. Try after a while.
TEN-PE raises exception: Too Many Requests. Rate limited. Try after a while.
MTUS raises exception: Too Many Requests. Rate limited. Try after a while.
BFS raises exception: Too Many Requests. Rate limited. Try after a while.
WRLD raises exception: Too Many Requests. Rate limited. Try after a while.
PLOW raises exception: Too Many Requests. Rate limited. Try after a while.
GOSS raises exception: Too Many Requests. Rate limited. Try after a while.
THFF raises exception: Too Many Requests. Rate limited. Try after a while.
SENEA raises exception: Too Many Requests. Rate limited. Try after a while.
CTLP raises exception: Too Many Requests. Rate limited. Try after a while.
SSYS raises exception: Too Many Requests. Rate limited. Try after a while.
LIND raises exception: Too Many Requests. Rate limited. Try after a while.
OPY raises exception: Too Many Requests. Rate limited. Try after a while.
HEPS raises exception: Too Many Requests. Rate limited. Try after a while.
BRSP raises exception: Too Many Requests. Rate limited. Try after a while.
RSKD raises exception: Too Many Requests. Rate limited. Try after a while.
VTS raises exception: Too Many Requests. Rate limited. Try after a while.
CCBG raises exception: Too Many Requests. Rate limited. Try after a while.
OPTU raises exception: Too Many Requests. Rate limited. Try after a while.
VEL raises exception: Too Many Requests. Rate limited. Try after a while.
HTBK raises exception: Too Many Requests. Rate limited. Try after a while.
RWT raises exception: Too Many Requests. Rate limited. Try after a while.
BTX raises exception: Too Many Requests. Rate limited. Try after a while.
ERII raises exception: Too Many Requests. Rate limited. Try after a while.
REPL raises exception: Too Many Requests. Rate limited. Try after a while.
SWIM raises exception: Too Many Requests. Rate limited. Try after a while.
KALV raises exception: Too Many Requests. Rate limited. Try after a while.
MPB raises exception: Too Many Requests. Rate limited. Try after a while.
LINC raises exception: Too Many Requests. Rate limited. Try after a while.
CUBB raises exception: Too Many Requests. Rate limited. Try after a while.
NPK raises exception: Too Many Requests. Rate limited. Try after a while.
SKYT raises exception: Too Many Requests. Rate limited. Try after a while.
AMSF raises exception: Too Many Requests. Rate limited. Try after a while.
MTA raises exception: Too Many Requests. Rate limited. Try after a while.
ESPR raises exception: Too Many Requests. Rate limited. Try after a while.
DGICA raises exception: Too Many Requests. Rate limited. Try after a while.
CLB raises exception: Too Many Requests. Rate limited. Try after a while.
AMRK raises exception: Too Many Requests. Rate limited. Try after a while.
NX raises exception: Too Many Requests. Rate limited. Try after a while.
INDI raises exception: Too Many Requests. Rate limited. Try after a while.
RIGL raises exception: Too Many Requests. Rate limited. Try after a while.
NBR raises exception: Too Many Requests. Rate limited. Try after a while.
ECC raises exception: Too Many Requests. Rate limited. Try after a while.
GSBC raises exception: Too Many Requests. Rate limited. Try after a while.
ATAI raises exception: Too Many Requests. Rate limited. Try after a while.
NXP raises exception: Too Many Requests. Rate limited. Try after a while.
CABO raises exception: Too Many Requests. Rate limited. Try after a while.
AEVA raises exception: Too Many Requests. Rate limited. Try after a while.
FOXF raises exception: Too Many Requests. Rate limited. Try after a while.
THH raises exception: Too Many Requests. Rate limited. Try after a while.
FVRR raises exception: Too Many Requests. Rate limited. Try after a while.
MCBS raises exception: Too Many Requests. Rate limited. Try after a while.
ORRF raises exception: Too Many Requests. Rate limited. Try after a while.
TMQ raises exception: Too Many Requests. Rate limited. Try after a while.
DJCO raises exception: Too Many Requests. Rate limited. Try after a while.
ORGO raises exception: Too Many Requests. Rate limited. Try after a while.
ODC raises exception: Too Many Requests. Rate limited. Try after a while.
GDOT raises exception: Too Many Requests. Rate limited. Try after a while.
MYE raises exception: Too Many Requests. Rate limited. Try after a while.
LXEO raises exception: Too Many Requests. Rate limited. Try after a while.
IBCP raises exception: Too Many Requests. Rate limited. Try after a while.
ATXS raises exception: Too Many Requests. Rate limited. Try after a while.
GDEN raises exception: Too Many Requests. Rate limited. Try after a while.
LWACU raises exception: Too Many Requests. Rate limited. Try after a while.
TRTX raises exception: Too Many Requests. Rate limited. Try after a while.
HSTM raises exception: Too Many Requests. Rate limited. Try after a while.
TREE raises exception: Too Many Requests. Rate limited. Try after a while.
YMT raises exception: Too Many Requests. Rate limited. Try after a while.
NXRT raises exception: Too Many Requests. Rate limited. Try after a while.
AHG raises exception: Too Many Requests. Rate limited. Try after a while.
NAT raises exception: Too Many Requests. Rate limited. Try after a while.
HTLD raises exception: Too Many Requests. Rate limited. Try after a while.
SMBC raises exception: Too Many Requests. Rate limited. Try after a while.
SES raises exception: Too Many Requests. Rate limited. Try after a while.
NCDL raises exception: Too Many Requests. Rate limited. Try after a while.
CRESY raises exception: Too Many Requests. Rate limited. Try after a while.
TROX raises exception: Too Many Requests. Rate limited. Try after a while.
TYG raises exception: Too Many Requests. Rate limited. Try after a while.
BBW raises exception: Too Many Requests. Rate limited. Try after a while.
PSNL raises exception: Too Many Requests. Rate limited. Try after a while.
SCHL raises exception: Too Many Requests. Rate limited. Try after a while.
MGRE raises exception: Too Many Requests. Rate limited. Try after a while.
CMPX raises exception: Too Many Requests. Rate limited. Try after a while.
WSR raises exception: Too Many Requests. Rate limited. Try after a while.
PROK raises exception: Too Many Requests. Rate limited. Try after a while.
MATV raises exception: Too Many Requests. Rate limited. Try after a while.
APEI raises exception: Too Many Requests. Rate limited. Try after a while.
ALTI raises exception: Too Many Requests. Rate limited. Try after a while.
VTLE raises exception: Too Many Requests. Rate limited. Try after a while.
TIPT raises exception: Too Many Requests. Rate limited. Try after a while.
CGNT raises exception: Too Many Requests. Rate limited. Try after a while.
AIOT raises exception: Too Many Requests. Rate limited. Try after a while.
HUYA raises exception: Too Many Requests. Rate limited. Try after a while.
ATHM raises exception: Too Many Requests. Rate limited. Try after a while.
SFIX raises exception: Too Many Requests. Rate limited. Try after a while.
KE raises exception: Too Many Requests. Rate limited. Try after a while.
NTGR raises exception: Too Many Requests. Rate limited. Try after a while.
CCCX raises exception: Too Many Requests. Rate limited. Try after a while.
ADTN raises exception: Too Many Requests. Rate limited. Try after a while.
ITRG raises exception: Too Many Requests. Rate limited. Try after a while.
LYEL raises exception: Too Many Requests. Rate limited. Try after a while.
CSV raises exception: Too Many Requests. Rate limited. Try after a while.
EMBC raises exception: Too Many Requests. Rate limited. Try after a while.
RGNX raises exception: Too Many Requests. Rate limited. Try after a while.
VALN raises exception: Too Many Requests. Rate limited. Try after a while.
WLKP raises exception: Too Many Requests. Rate limited. Try after a while.
GROY raises exception: Too Many Requests. Rate limited. Try after a while.
FDUS raises exception: Too Many Requests. Rate limited. Try after a while.
CTEV raises exception: Too Many Requests. Rate limited. Try after a while.
VTEX raises exception: Too Many Requests. Rate limited. Try after a while.
ADAM raises exception: Too Many Requests. Rate limited. Try after a while.
SMBK raises exception: Too Many Requests. Rate limited. Try after a while.
GRPN raises exception: Too Many Requests. Rate limited. Try after a while.
CRML raises exception: Too Many Requests. Rate limited. Try after a while.
SSTK raises exception: Too Many Requests. Rate limited. Try after a while.
KRUS raises exception: Too Many Requests. Rate limited. Try after a while.
KODK raises exception: Too Many Requests. Rate limited. Try after a while.
GHM raises exception: Too Many Requests. Rate limited. Try after a while.
GYRE raises exception: Too Many Requests. Rate limited. Try after a while.
TEN raises exception: Too Many Requests. Rate limited. Try after a while.
SPFI raises exception: Too Many Requests. Rate limited. Try after a while.
SKYH raises exception: Too Many Requests. Rate limited. Try after a while.
FCBC raises exception: Too Many Requests. Rate limited. Try after a while.
EBS raises exception: Too Many Requests. Rate limited. Try after a while.
WBI raises exception: Too Many Requests. Rate limited. Try after a while.
CRSR raises exception: Too Many Requests. Rate limited. Try after a while.
AIP raises exception: Too Many Requests. Rate limited. Try after a while.
NEWTH raises exception: Too Many Requests. Rate limited. Try after a while.
FULC raises exception: Too Many Requests. Rate limited. Try after a while.
CTMX raises exception: Too Many Requests. Rate limited. Try after a while.
FISI raises exception: Too Many Requests. Rate limited. Try after a while.
PRAA raises exception: Too Many Requests. Rate limited. Try after a while.
TCMD raises exception: Too Many Requests. Rate limited. Try after a while.
EGBN raises exception: Too Many Requests. Rate limited. Try after a while.
SPT raises exception: Too Many Requests. Rate limited. Try after a while.
AXTI raises exception: Too Many Requests. Rate limited. Try after a while.
BTBT raises exception: Too Many Requests. Rate limited. Try after a while.
DCBO raises exception: Too Many Requests. Rate limited. Try after a while.
GILT raises exception: Too Many Requests. Rate limited. Try after a while.
OMER raises exception: Too Many Requests. Rate limited. Try after a while.
ADSE raises exception: Too Many Requests. Rate limited. Try after a while.
UXIN raises exception: Too Many Requests. Rate limited. Try after a while.
KRNT raises exception: Too Many Requests. Rate limited. Try after a while.
DC raises exception: Too Many Requests. Rate limited. Try after a while.
GPRE raises exception: Too Many Requests. Rate limited. Try after a while.
NEWP raises exception: Too Many Requests. Rate limited. Try after a while.
HKD raises exception: Too Many Requests. Rate limited. Try after a while.
RCAT raises exception: Too Many Requests. Rate limited. Try after a while.
HIFS raises exception: Too Many Requests. Rate limited. Try after a while.
AEHR raises exception: Too Many Requests. Rate limited. Try after a while.
NFGC raises exception: Too Many Requests. Rate limited. Try after a while.
BZH raises exception: Too Many Requests. Rate limited. Try after a while.
MGTX raises exception: Too Many Requests. Rate limited. Try after a while.
BCAL raises exception: Too Many Requests. Rate limited. Try after a while.
EICC raises exception: Too Many Requests. Rate limited. Try after a while.
IIIN raises exception: Too Many Requests. Rate limited. Try after a while.

In [12]:
# -----------------------------------------
# Get all US-traded stocks with market cap > $750M using FMP API
# Iterates by sector to avoid 1000 record limit per request
# -----------------------------------------

FMP_API_KEY = "UdRiHSXViYG3qI0ChXrlhVRvqOPXRAB5"

# All GICS sectors
SECTORS = [
    "Technology",
    "Healthcare", 
    "Financial Services",
    "Consumer Cyclical",
    "Communication Services",
    "Industrials",
    "Consumer Defensive",
    "Energy",
    "Basic Materials",
    "Real Estate",
    "Utilities"
]


def get_stocks_by_sector(sector, min_mcap_millions=750, api_key=FMP_API_KEY):
    """
    Get all US stocks in a specific sector above market cap threshold.
    Uses 1 API call per sector.
    """
    import time
    
    url = "https://financialmodelingprep.com/stable/company-screener"
    params = {
        "marketCapMoreThan": int(min_mcap_millions * 1e6),
        "isActivelyTrading": True,
        "isEtf": False,
        "isFund": False,
        "exchange": "NYSE,NASDAQ,AMEX",
        "sector": sector,
        "apikey": api_key
    }
    
    try:
        response = requests.get(url, params=params, timeout=30)
        
        if response.status_code != 200:
            print(f"  Error for {sector}: {response.status_code}")
            return pd.DataFrame()
        
        data = response.json()
        
        if isinstance(data, dict) and 'Error Message' in data:
            print(f"  API Error for {sector}: {data['Error Message']}")
            return pd.DataFrame()
        
        df = pd.DataFrame(data)
        print(f"  {sector}: {len(df)} stocks")
        
        # Small delay to avoid rate limiting
        time.sleep(0.5)
        
        return df
        
    except Exception as e:
        print(f"  Exception for {sector}: {e}")
        return pd.DataFrame()


def get_us_stocks_fmp(min_mcap_millions=750, api_key=FMP_API_KEY):
    """
    Get all US stocks above market cap threshold by iterating through sectors.
    Uses ~11 API calls (1 per sector).
    """
    all_stocks = []
    
    print(f"Fetching stocks with market cap >= ${min_mcap_millions}M by sector...")
    print(f"This will use {len(SECTORS)} API calls.\n")
    
    for sector in SECTORS:
        df = get_stocks_by_sector(sector, min_mcap_millions, api_key)
        if not df.empty:
            all_stocks.append(df)
    
    if not all_stocks:
        raise Exception("No data retrieved from any sector")
    
    # Combine all sectors
    df = pd.concat(all_stocks, ignore_index=True)
    df.drop(columns=["exchange"])
    
    # Clean up columns
    df = df.rename(columns={
        'symbol': 'ticker',
        'companyName': 'name', 
        'marketCap': 'market_cap',
        'exchangeShortName': 'exchange'
    })
    
    # Select relevant columns (handle both old and new API response formats)
    possible_cols = ['ticker', 'name', 'market_cap', 'sector', 'industry', 'exchange', 
                     'country', 'price', 'beta', 'volume']
    cols = [c for c in possible_cols if c in df.columns]
    df = df[cols]
    
    # Remove duplicates (in case any stock appears in multiple sectors)
    df = df.drop_duplicates(subset=['ticker'])
    
    # Sort by market cap
    df = df.sort_values('market_cap', ascending=False).reset_index(drop=True)
    
    print(f"\n=== Total: {len(df)} unique stocks ===")
    return df


def load_or_fetch_universe(csv_path, min_mcap_millions=750, api_key=FMP_API_KEY, refresh=False):
    """
    Load ticker universe from CSV if it exists, otherwise fetch from FMP and save.
    """
    if os.path.exists(csv_path) and not refresh:
        print(f"Loading universe from {csv_path}")
        df = pd.read_csv(csv_path)
        print(f"Loaded {len(df)} tickers")
        return df
    
    print("Fetching fresh universe from FMP API...")
    df = get_us_stocks_fmp(min_mcap_millions, api_key)
    
    # Save to CSV
    df.to_csv(csv_path, index=False)
    print(f"Saved universe to {csv_path}")
    
    return df


# ============================================================
# Fetch and save the universe (uses ~11 API calls if CSV doesn't exist)
# ============================================================

UNIVERSE_CSV = "us_stocks_500m.csv"
MIN_MCAP = 500  # millions USD

# Set refresh=True to force a fresh fetch from FMP
stocks_df = load_or_fetch_universe(UNIVERSE_CSV, min_mcap_millions=MIN_MCAP, refresh=False)

display(stocks_df.head(10))
print(f"\nTotal tickers: {len(stocks_df)}")
print(f"\nSector distribution:")
display(stocks_df['sector'].value_counts())

Loading universe from us_stocks_500m.csv
Loaded 3098 tickers

,ticker,name,market_cap,sector,industry,exchange,exchange.1,country,price,beta,volume
0,NVDA,NVIDIA Corporation,4239786770335,Technology,Semiconductors,NASDAQ Global Select,NASDAQ,US,174.14,2.284,173661029
1,AAPL,Apple Inc.,4021975523070,Technology,Consumer Electronics,NASDAQ Global Select,NASDAQ,US,272.19,1.107,51509672
2,GOOG,Alphabet Inc.,3665542911390,Technology,Internet Content & Information,NASDAQ Global Select,NASDAQ,US,303.75,1.070,19859779
3,GOOGL,Alphabet Inc.,3649975667421,Technology,Internet Content & Information,NASDAQ Global Select,NASDAQ,US,302.46,1.070,32122646
4,MSFT,Microsoft Corporation,3597428078164,Technology,Software - Infrastructure,NASDAQ Global Select,NASDAQ,US,483.98,1.070,26736126
5,AMZN,"Amazon.com, Inc.",2423979947546,Consumer Cyclical,Specialty Retail,NASDAQ Global Select,NASDAQ,US,226.76,1.372,48340627
6,META,"Meta Platforms, Inc.",1674802780326,Technology,Internet Content & Information,NASDAQ Global Select,NASDAQ,US,664.45,1.273,19001162
7,TSLA,"Tesla, Inc.",1556592330390,Consumer Cyclical,Auto - Manufacturers,NASDAQ Global Select,NASDAQ,US,483.37,1.878,94595726
8,AVGO,Broadcom Inc.,1554436009092,Technology,Semiconductors,NASDAQ Global Select,NASDAQ,US,329.88,1.204,51123858
9,TSM,Taiwan Semiconductor Manufacturing Company Lim...,1476499408065,Technology,Semiconductors,New York Stock Exchange,NYSE,TW,284.68,1.267,11182194

Total tickers: 3098

Sector distribution:

sector
Financial Services        557
Technology                446
Healthcare                445
Industrials               400
Consumer Cyclical         319
Real Estate               188
Energy                    187
Basic Materials           178
Communication Services    139
Consumer Defensive        132
Utilities                 107
Name: count, dtype: int64

In [13]:
# -----------------------------------------
# Fetch OHLCV data using yfinance (free, unlimited)
# -----------------------------------------
import time

def get_stock_ohlcv(ticker, start_date, end_date, interval="1d"):
    """
    Downloads OHLCV data for a single ticker from Yahoo Finance.
    
    Args:
        ticker (str): Stock ticker symbol
        start_date (str): "YYYY-MM-DD"
        end_date (str): "YYYY-MM-DD"
        interval (str): Data frequency
    
    Returns:
        pandas.DataFrame: OHLCV data
    """
    try:
        stock = yf.Ticker(ticker)
        df = stock.history(start=start_date, end=end_date, interval=interval)
        if df.empty:
            print(f'{ticker} empty')
        if not df.empty:
            df = df.drop(columns=['Dividends', 'Stock Splits'], errors='ignore')
        return df
    except Exception as e:
        print(f'{ticker} raises exception: {e}')
        return pd.DataFrame()


def get_all_stocks_ohlcv(tickers, start_date, end_date, interval="1d", max_workers=5, sleep_time=0.2):
    """
    Downloads OHLCV data for multiple tickers in parallel using yfinance.
    Includes sleep between requests to avoid rate limiting.
    
    Args:
        tickers (list): List of ticker symbols
        start_date (str): "YYYY-MM-DD"
        end_date (str): "YYYY-MM-DD"
        interval (str): Data frequency
        max_workers (int): Number of parallel threads (lower = less rate limiting)
        sleep_time (float): Seconds to sleep between each request
    
    Returns:
        dict: Dictionary mapping ticker -> DataFrame
    """
    all_data = {}
    failed_tickers = []
    
    def fetch_ticker(ticker):
        time.sleep(sleep_time)  # Sleep to avoid rate limiting
        df = get_stock_ohlcv(ticker, start_date, end_date, interval)
        return ticker, df
    
    print(f"Fetching OHLCV data for {len(tickers)} tickers from {start_date} to {end_date}...")
    print(f"Using {max_workers} workers with {sleep_time}s delay between requests...")
    
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(fetch_ticker, ticker): ticker for ticker in tickers}
        for future in tqdm(as_completed(futures), total=len(futures), desc="Downloading"):
            ticker, df = future.result()
            if not df.empty:
                all_data[ticker] = df
            else:
                failed_tickers.append(ticker)
    
    print(f"Successfully fetched: {len(all_data)} tickers")
    print(f"Failed/empty: {len(failed_tickers)} tickers")
    
    return all_data, failed_tickers


def calculate_returns(stock_data, periods=[1, 5, 10, 21]):
    """
    Calculate log returns for all tickers at specified periods.
    
    Args:
        stock_data (dict): Dictionary mapping ticker -> OHLCV DataFrame
        periods (list): List of periods for return calculation (in trading days)
    
    Returns:
        pd.DataFrame: Wide DataFrame with returns for all tickers
    """
    returns_list = []
    
    for ticker, df in stock_data.items():
        if df.empty or 'Close' not in df.columns:
            continue
            
        ticker_returns = pd.DataFrame(index=df.index)
        ticker_returns['ticker'] = ticker
        
        for period in periods:
            ticker_returns[f'ret_{period}d'] = np.log(df['Close'] / df['Close'].shift(period))
        
        returns_list.append(ticker_returns)
    
    if not returns_list:
        return pd.DataFrame()
    
    # Combine all returns
    all_returns = pd.concat(returns_list, axis=0)
    all_returns = all_returns.reset_index().rename(columns={'index': 'date', 'Date': 'date'})
    
    return all_returns


def save_to_csv(df, csv_path):
    """Save returns DataFrame to CSV."""
    df.to_csv(csv_path, index=False)
    print(f"Saved returns data to {csv_path}")


# ============================================================
# Fetch OHLCV data and calculate returns
# ============================================================

# Configuration
START_DATE = "2018-01-01"
END_DATE = "2026-02-13"
RETURN_PERIODS = [1, 5, 10, 21, 63]  # 1d, 1wk, 2wk, 1mo, 3mo
OHLCV_CSV = "stock_ohlcv_data.csv"
RETURNS_CSV = "stock_returns.csv"

# Get list of tickers from universe
tickers = stocks_df['ticker'].tolist()

# Fetch all OHLCV data with rate limiting protection
stock_data, failed_tickers = get_all_stocks_ohlcv(
    tickers, 
    START_DATE, 
    END_DATE, 
    interval="1d", 
    max_workers=1,
    sleep_time=0.5
)

# Calculate returns
returns_df = calculate_returns(stock_data, periods=RETURN_PERIODS)
print(f"\nReturns DataFrame shape: {returns_df.shape}")

# Save returns to CSV
save_to_csv(returns_df, RETURNS_CSV)

# Show summary
print(f"\n=== Summary ===")
print(f"Date range: {START_DATE} to {END_DATE}")
print(f"Tickers with data: {returns_df['ticker'].nunique()}")
print(f"Total rows: {len(returns_df)}")
print(f"Return periods: {RETURN_PERIODS}")

Fetching OHLCV data for 3098 tickers from 2018-01-01 to 2026-02-13...
Using 1 workers with 0.5s delay between requests...

Downloading:   5%|▍         | 143/3098 [01:32<31:45,  1.55it/s]$CMCSV: possibly delisted; no timezone found
Downloading:   5%|▍         | 144/3098 [01:33<31:25,  1.57it/s]

CMCSV empty

Downloading:   5%|▌         | 160/3098 [01:43<32:22,  1.51it/s]$MMC: possibly delisted; no timezone found
Downloading:   5%|▌         | 161/3098 [01:44<32:08,  1.52it/s]

MMC empty

Downloading:  16%|█▋        | 505/3098 [05:23<27:24,  1.58it/s]$EBR: possibly delisted; no timezone found
Downloading:  16%|█▋        | 506/3098 [05:24<27:09,  1.59it/s]

EBR empty

Downloading:  28%|██▊       | 855/3098 [09:04<23:53,  1.56it/s]$ERJ: possibly delisted; no timezone found
Downloading:  28%|██▊       | 856/3098 [09:05<24:20,  1.53it/s]

ERJ empty

Downloading:  31%|███       | 964/3098 [10:14<22:23,  1.59it/s]$RNA: possibly delisted; no price data found  (1d 2018-01-01 -> 2026-02-13) (Yahoo error = "Data doesn't exist for startDate = 1514782800, endDate = 1770958800")
Downloading:  31%|███       | 965/3098 [10:14<22:35,  1.57it/s]

RNA empty

Downloading:  36%|███▌      | 1115/3098 [11:50<21:30,  1.54it/s]$ELP: possibly delisted; no timezone found
Downloading:  36%|███▌      | 1116/3098 [11:51<21:43,  1.52it/s]

ELP empty

Downloading:  36%|███▌      | 1122/3098 [11:55<20:34,  1.60it/s]$MRUS: possibly delisted; no timezone found
Downloading:  36%|███▌      | 1123/3098 [11:55<20:50,  1.58it/s]

MRUS empty

Downloading:  36%|███▋      | 1126/3098 [11:57<20:43,  1.59it/s]$SNV: possibly delisted; no timezone found
Downloading:  36%|███▋      | 1127/3098 [11:58<21:01,  1.56it/s]

SNV empty

Downloading:  38%|███▊      | 1163/3098 [12:21<20:23,  1.58it/s]$ZK: possibly delisted; no timezone found
Downloading:  38%|███▊      | 1164/3098 [12:21<20:25,  1.58it/s]

ZK empty

Downloading:  38%|███▊      | 1165/3098 [12:22<20:38,  1.56it/s]$VSNTV: possibly delisted; no timezone found
Downloading:  38%|███▊      | 1166/3098 [12:23<20:39,  1.56it/s]

VSNTV empty

Downloading:  42%|████▏     | 1294/3098 [13:44<19:02,  1.58it/s]$CDTX: possibly delisted; no timezone found
Downloading:  42%|████▏     | 1295/3098 [13:44<18:54,  1.59it/s]

CDTX empty

Downloading:  42%|████▏     | 1301/3098 [13:48<19:06,  1.57it/s]$DOOO: possibly delisted; no timezone found
Downloading:  42%|████▏     | 1302/3098 [13:49<19:10,  1.56it/s]

DOOO empty

Downloading:  46%|████▌     | 1423/3098 [15:06<18:11,  1.53it/s]$SPR: possibly delisted; no timezone found
Downloading:  46%|████▌     | 1424/3098 [15:07<18:07,  1.54it/s]

SPR empty

Downloading:  47%|████▋     | 1449/3098 [15:23<17:07,  1.61it/s]$AKRO: possibly delisted; no timezone found
Downloading:  47%|████▋     | 1450/3098 [15:23<17:13,  1.59it/s]

AKRO empty

Downloading:  50%|████▉     | 1540/3098 [16:20<16:36,  1.56it/s]$COMM: possibly delisted; no timezone found
Downloading:  50%|████▉     | 1541/3098 [16:20<16:40,  1.56it/s]

COMM empty

Downloading:  50%|████▉     | 1543/3098 [16:22<16:46,  1.54it/s]$ALE: possibly delisted; no timezone found
Downloading:  50%|████▉     | 1544/3098 [16:22<16:40,  1.55it/s]

ALE empty

Downloading:  52%|█████▏    | 1616/3098 [17:08<14:44,  1.68it/s]$GRP-UN: possibly delisted; no timezone found
Downloading:  52%|█████▏    | 1617/3098 [17:09<15:06,  1.63it/s]

GRP-UN empty

Downloading:  55%|█████▌    | 1708/3098 [18:07<14:25,  1.61it/s]$KAR: possibly delisted; no timezone found
Downloading:  55%|█████▌    | 1709/3098 [18:07<14:45,  1.57it/s]

KAR empty

Downloading:  58%|█████▊    | 1805/3098 [19:08<13:40,  1.58it/s]$BWSN: possibly delisted; no timezone found
Downloading:  58%|█████▊    | 1806/3098 [19:08<13:43,  1.57it/s]

BWSN empty

Downloading:  62%|██████▏   | 1916/3098 [20:18<12:01,  1.64it/s]$SPNS: possibly delisted; no timezone found
Downloading:  62%|██████▏   | 1917/3098 [20:18<12:24,  1.59it/s]

SPNS empty

Downloading:  63%|██████▎   | 1953/3098 [20:41<11:34,  1.65it/s]$HBI: possibly delisted; no timezone found
Downloading:  63%|██████▎   | 1954/3098 [20:42<11:48,  1.61it/s]

HBI empty

Downloading:  64%|██████▍   | 1983/3098 [21:00<11:35,  1.60it/s]$MODG: possibly delisted; no timezone found
Downloading:  64%|██████▍   | 1984/3098 [21:01<11:35,  1.60it/s]

MODG empty

Downloading:  68%|██████▊   | 2110/3098 [22:20<10:37,  1.55it/s]$SCS: possibly delisted; no timezone found
Downloading:  68%|██████▊   | 2111/3098 [22:21<10:30,  1.57it/s]

SCS empty

Downloading:  70%|███████   | 2169/3098 [22:58<11:16,  1.37it/s]$IAS: possibly delisted; no price data found  (1d 2018-01-01 -> 2026-02-13)
Downloading:  70%|███████   | 2170/3098 [22:59<10:24,  1.49it/s]

IAS empty

Downloading:  71%|███████   | 2205/3098 [23:21<09:34,  1.55it/s]$HOUS: possibly delisted; no timezone found
Downloading:  71%|███████   | 2206/3098 [23:22<09:47,  1.52it/s]

HOUS empty

Downloading:  74%|███████▎  | 2280/3098 [24:09<08:40,  1.57it/s]$PGRE: possibly delisted; no timezone found
Downloading:  74%|███████▎  | 2281/3098 [24:10<08:43,  1.56it/s]

PGRE empty

Downloading:  78%|███████▊  | 2425/3098 [25:43<07:12,  1.56it/s]$HSII: possibly delisted; no timezone found
Downloading:  78%|███████▊  | 2426/3098 [25:43<07:15,  1.54it/s]

HSII empty

Downloading:  80%|████████  | 2488/3098 [26:24<06:39,  1.53it/s]$PRO: possibly delisted; no timezone found
Downloading:  80%|████████  | 2489/3098 [26:25<06:41,  1.52it/s]

PRO empty

Downloading:  84%|████████▍ | 2597/3098 [27:36<05:26,  1.54it/s]$CGBDL: possibly delisted; no price data found  (1d 2018-01-01 -> 2026-02-13)
Downloading:  84%|████████▍ | 2598/3098 [27:37<05:15,  1.58it/s]

CGBDL empty

Downloading:  84%|████████▍ | 2615/3098 [27:48<05:08,  1.57it/s]$CVAC: possibly delisted; no timezone found
Downloading:  84%|████████▍ | 2616/3098 [27:49<05:13,  1.54it/s]

CVAC empty

Downloading:  85%|████████▍ | 2629/3098 [27:58<05:23,  1.45it/s]$MNMD: possibly delisted; no timezone found
Downloading:  85%|████████▍ | 2630/3098 [27:58<05:14,  1.49it/s]

MNMD empty

Downloading:  87%|████████▋ | 2701/3098 [28:46<04:21,  1.52it/s]$ABL: possibly delisted; no timezone found
Downloading:  87%|████████▋ | 2702/3098 [28:47<04:17,  1.54it/s]

ABL empty

Downloading:  88%|████████▊ | 2713/3098 [28:54<04:14,  1.51it/s]$ODP: possibly delisted; no timezone found
Downloading:  88%|████████▊ | 2714/3098 [28:55<04:13,  1.52it/s]

ODP empty

Downloading:  88%|████████▊ | 2740/3098 [29:12<03:51,  1.55it/s]$ATUS: possibly delisted; no timezone found
Downloading:  88%|████████▊ | 2741/3098 [29:13<03:49,  1.56it/s]

ATUS empty

$GCI: possibly delisted; no timezone found
Downloading:  89%|████████▊ | 2742/3098 [29:13<03:47,  1.56it/s]

GCI empty

Downloading:  91%|█████████ | 2809/3098 [29:58<03:14,  1.48it/s]$AMRK: possibly delisted; no timezone found
Downloading:  91%|█████████ | 2810/3098 [29:58<03:09,  1.52it/s]

AMRK empty

Downloading:  92%|█████████▏| 2860/3098 [30:32<02:33,  1.55it/s]$VTLE: possibly delisted; no timezone found
Downloading:  92%|█████████▏| 2861/3098 [30:32<02:30,  1.57it/s]

VTLE empty

Downloading:  95%|█████████▍| 2932/3098 [31:18<01:44,  1.58it/s]$EICB: possibly delisted; no timezone found
Downloading:  95%|█████████▍| 2933/3098 [31:19<01:45,  1.57it/s]

EICB empty

Downloading:  95%|█████████▌| 2951/3098 [31:30<01:28,  1.66it/s]$QD: possibly delisted; no timezone found
Downloading:  95%|█████████▌| 2952/3098 [31:31<01:29,  1.62it/s]

QD empty

Downloading:  96%|█████████▌| 2974/3098 [31:44<01:15,  1.64it/s]$CRESW: possibly delisted; no price data found  (1d 2018-01-01 -> 2026-02-13) (Yahoo error = "Data doesn't exist for startDate = 1514782800, endDate = 1770958800")
Downloading:  96%|█████████▌| 2975/3098 [31:45<01:15,  1.63it/s]

CRESW empty

Downloading:  99%|█████████▉| 3068/3098 [32:47<00:20,  1.50it/s]$NVAWW: possibly delisted; no price data found  (1d 2018-01-01 -> 2026-02-13) (Yahoo error = "Data doesn't exist for startDate = 1514782800, endDate = 1770958800")
Downloading:  99%|█████████▉| 3069/3098 [32:47<00:19,  1.50it/s]

NVAWW empty

Downloading:  99%|█████████▉| 3072/3098 [32:49<00:16,  1.57it/s]$CLCO: possibly delisted; no timezone found
Downloading:  99%|█████████▉| 3073/3098 [32:50<00:15,  1.58it/s]

CLCO empty

Downloading: 100%|██████████| 3098/3098 [33:07<00:00,  1.56it/s]

Successfully fetched: 3056 tickers
Failed/empty: 42 tickers

Returns DataFrame shape: (5387851, 7)
Saved returns data to stock_returns.csv

=== Summary ===
Date range: 2018-01-01 to 2026-02-13
Tickers with data: 3056
Total rows: 5387851
Return periods: [1, 5, 10, 21, 63]

In [14]:
# def stock_data_to_df(stock_data):
#     """
#     Convert stock_data dict to a single DataFrame with ticker column.
#     """
#     dfs = []
#     for ticker, df in stock_data.items():
#         if df.empty:
#             continue
#         df = df.copy()
#         df['ticker'] = ticker
#         df = df.reset_index().rename(columns={'index': 'date', 'Date': 'date'})
#         dfs.append(df)
    
#     if not dfs:
#         return pd.DataFrame()
    
#     combined = pd.concat(dfs, ignore_index=True)
#     cols = ['date', 'ticker', 'Open', 'High', 'Low', 'Close', 'Volume']
#     cols = [c for c in cols if c in combined.columns]
#     return combined[cols]


# if len(failed_tickers) > 0:
#     print(f"Retrying {len(failed_tickers)} failed tickers...")
#     print("Waiting 30 seconds before retry to avoid rate limiting...")
#     time.sleep(30)
    
#     # Retry failed tickers
#     retry_data, still_failed = get_all_stocks_ohlcv(
#         failed_tickers, 
#         START_DATE, 
#         END_DATE, 
#         interval="1d", 
#         max_workers=20
#     )
    
#     # If we got new data, append to CSV
#     if len(retry_data) > 0:
#         retry_df = stock_data_to_df(retry_data)
#         print(f"\nRetry recovered: {len(retry_data)} tickers")
        
#         # Append to existing CSV
#         retry_df.to_csv(OHLCV_CSV, mode='a', header=False, index=False)
#         print(f"Appended retry data to {OHLCV_CSV}")
        
#         # Update stock_data with recovered tickers
#         stock_data.update(retry_data)
        
#         # Update failed_tickers list
#         failed_tickers = still_failed
    
#     print(f"\n=== After Retry ===")
#     print(f"Total successful: {len(stock_data)} tickers")
#     print(f"Still failed: {len(failed_tickers)} tickers")
# else:
#     print("No failed tickers to retry!")

In [15]:
# -----------------------------------------
# Convert stock_data dict to DataFrame and save to CSV
# -----------------------------------------

def stock_data_to_df(stock_data):
    """
    Convert stock_data dict to a single DataFrame with ticker column.
    
    Args:
        stock_data (dict): Dictionary mapping ticker -> OHLCV DataFrame
    
    Returns:
        pd.DataFrame: Combined DataFrame with columns: date, ticker, Open, High, Low, Close, Volume
    """
    dfs = []
    for ticker, df in stock_data.items():
        if df.empty:
            continue
        df = df.copy()
        df['ticker'] = ticker
        df = df.reset_index().rename(columns={'index': 'date', 'Date': 'date'})
        dfs.append(df)
    
    if not dfs:
        return pd.DataFrame()
    
    combined = pd.concat(dfs, ignore_index=True)
    # Reorder columns
    cols = ['date', 'ticker', 'Open', 'High', 'Low', 'Close', 'Volume']
    cols = [c for c in cols if c in combined.columns]
    return combined[cols]


# Convert and save OHLCV data
ohlcv_df = stock_data_to_df(stock_data)
print(f"OHLCV DataFrame shape: {ohlcv_df.shape}")
print(f"Unique tickers: {ohlcv_df['ticker'].nunique()}")

# Save to CSV
ohlcv_df.to_csv(OHLCV_CSV, index=False)
print(f"\nSaved OHLCV data to {OHLCV_CSV}")

OHLCV DataFrame shape: (5387851, 7)
Unique tickers: 3056

Saved OHLCV data to stock_ohlcv_data.csv

In [16]:
# -----------------------------------------
# Analyze failed tickers by market cap
# -----------------------------------------

# Get failed tickers info from universe
failed_df = stocks_df[stocks_df['ticker'].isin(failed_tickers)].copy()

print(f"Total failed tickers: {len(failed_tickers)}")
print(f"Failed tickers found in universe: {len(failed_df)}")

# Analyze by market cap thresholds
mcap_thresholds = [500, 750, 1000, 2000, 5000, 10000]  # in millions

print("\n=== Failed Tickers by Market Cap ===")
for threshold in mcap_thresholds:
    threshold_dollars = threshold * 1e6
    count = len(failed_df[failed_df['market_cap'] >= threshold_dollars])
    print(f"Market cap >= ${threshold}M: {count} failed tickers")

# Show top failed tickers by market cap
print("\n=== Top 20 Failed Tickers by Market Cap ===")
display(failed_df.nlargest(20, 'market_cap')[['ticker', 'name', 'market_cap', 'sector', 'industry']])

# Sector breakdown of failed tickers
print("\n=== Failed Tickers by Sector ===")
display(failed_df['sector'].value_counts())

Total failed tickers: 42
Failed tickers found in universe: 42

=== Failed Tickers by Market Cap ===
Market cap >= $500M: 42 failed tickers
Market cap >= $750M: 35 failed tickers
Market cap >= $1000M: 28 failed tickers
Market cap >= $2000M: 22 failed tickers
Market cap >= $5000M: 12 failed tickers
Market cap >= $10000M: 4 failed tickers

=== Top 20 Failed Tickers by Market Cap ===

,ticker,name,market_cap,sector,industry
143,CMCSV,Comcast Corporation Class A Common Stock Ex-Di...,103527671695,Consumer Cyclical,Broadcasting
160,MMC,"Marsh & McLennan Companies, Inc.",91379602780,Financial Services,Insurance - Brokers
505,EBR,Centrais Elétricas Brasileiras S.A. - Eletrobrás,25577232356,Utilities,Regulated Electric
855,ERJ,Embraer S.A.,11845015303,Industrials,Aerospace & Defense
964,RNA,"Avidity Biosciences, Inc.",9467378489,Healthcare,Biotechnology
1115,ELP,Companhia Paranaense de Energia - COPEL,7394384487,Utilities,Diversified Utilities
1122,MRUS,Merus N.V.,7341469300,Healthcare,Biotechnology
1126,SNV,Synovus Financial Corp.,7253110241,Financial Services,Banks - Regional
1163,ZK,ZEEKR Intelligent Technology Holding Limited,6814196533,Consumer Cyclical,Auto - Manufacturers
1165,VSNTV,"Versant Media Group, Inc. Class A Common Stock...",6775050893,Communication Services,Entertainment
1294,CDTX,"Cidara Therapeutics, Inc.",5587657335,Healthcare,Biotechnology
1301,DOOO,BRP Inc.,5517365912,Consumer Cyclical,Auto - Recreational Vehicles
1423,SPR,"Spirit AeroSystems Holdings, Inc.",4637297077,Industrials,Aerospace & Defense
1449,AKRO,"Akero Therapeutics, Inc.",4498738105,Healthcare,Biotechnology
1540,COMM,"CommScope Holding Company, Inc.",3954644420,Technology,Communication Equipment
1543,ALE,"ALLETE, Inc.",3943712122,Utilities,Diversified Utilities
1616,GRP-UN,Granite Real Estate Investment Trust,3591833828,Real Estate,REIT - Industrial
1708,KAR,"OPENLANE, Inc.",3154954022,Consumer Cyclical,Auto - Dealerships
1805,BWSN,"Babcock & Wilcox Enterprises, I",2797498000,Technology,Consumer Electronics
1916,SPNS,Sapiens International Corporation N.V.,2428882678,Technology,Software - Application

=== Failed Tickers by Sector ===

sector
Consumer Cyclical         7
Financial Services        7
Industrials               6
Healthcare                6
Communication Services    4
Technology                4
Utilities                 3
Real Estate               3
Energy                    1
Basic Materials           1
Name: count, dtype: int64